name: Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Download and set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: 30.0.3
    - name: Install dependencies
      run: ./gradlew dependencies
    - name: Build
      run: ./gradlew build
    - name: Start emulator
      run: |
        $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
        adb wait-for-device
    - name: Run tests
      run: ./gradlew connectedAndroidTest