name: iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_12.5.app
    - name: Install dependencies
      run: bundle install
    - name: Install CocoaPods
      run: pod install
    - name: Build
      run: xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5' build
    - name: Run tests
      run: xcodebuild test -workspace YourApp.xcworkspace -scheme YourApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5'